// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Safra.Domain.Entities
{
    public partial class tab_parcela : BaseEntity
    {
        public int idParcela { get; set; }
        public int idFinanciamento { get; set; }
        public int num_parcela { get; set; }
        public decimal vl_parcela { get; set; }
        public DateTime dt_venc_parcela { get; set; }
        public DateTime? dt_pgto_parcela { get; set; }

        public virtual tab_financiamento idFinanciamentoNavigation { get; set; }
    }
}