// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Safra.Domain.Entities
{
    public partial class tab_financiamento : BaseEntity
    {
        public tab_financiamento()
        {
            tab_parcela = new HashSet<tab_parcela>();
        }

        public int idFinanciamento { get; set; }
        public int idTipoCredito { get; set; }
        public int idCliente { get; set; }
        public decimal vl_total { get; set; }
        public DateTime? dt_ultimo_vencimento { get; set; }

        public virtual tab_cliente idClienteNavigation { get; set; }
        public virtual tab_tipo_credito idTipoCreditoNavigation { get; set; }
        public virtual ICollection<tab_parcela> tab_parcela { get; set; }
    }
}